name: nearlydailystartups
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4218831022735685
title: Nearly Daily Startups
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73404364-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0166bf'
    - '#ffffff'
    - '#e5eff8'
    - '#3585cc'
    - '#7aafdd'
  brandStrength: 0.875
  lightness: 0.8399193584918976
  saturation: 0.5945972870104015
  rhythmicContrast: 0.1632512346841395
purpose: []
