name: nearlydailystartups
favicon: null
layout_spectrum: 0.4662235900759697
typography_spectrum: 0.4218831022735685
title: Nearly Daily Startups
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73404364-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.051871240604668856
  lightness: 0.8399193584918976
  saturation: 0.5945972870104015
  rhythmicContrast: 0.1632512346841395
purpose: []
